# version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: ci3_web
    ports:
      - "8085:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
      - api
      - websocket
    networks:
      - ci3net

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ci3_api
    ports:
      - "8086:80"
    volumes:
      - ./api:/var/www/html
      - ./scripts:/var/www/html/scripts
      - ./migrations:/var/www/html/migrations
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=ci3_db
    depends_on:
      - db
    networks:
      - ci3net

  websocket:
    build:
      context: ./websocket
    container_name: ci3_websocket
    ports:
      - "8080:8080"
    volumes:
    - ./websocket:/app 
    networks:
      - ci3net

  db:
    image: mysql:5.7
    container_name: ci3_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ci3net

networks:
  ci3net:

volumes:
  db_data:
