version: '3.8'

services:
  app:
    build: .
    container_name: ci3_app
    ports:
      - "8085:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - ci3net

  db:
    image: mysql:5.7
    container_name: ci3_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ci3net
  migrate:
    image: mysql:5.7
    depends_on:
      - db
    entrypoint: [ "sh", "-c", "./scripts/migrate.sh" ]
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./migrations:/migrations
      - ./scripts:/scripts
    networks:
      - ci3net

networks:
  ci3net:

volumes:
  db_data:
