FROM php:7.4-apache

RUN a2enmod rewrite
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN apt-get update && apt-get install -y \
    default-mysql-client

COPY ./api /var/www/html/
RUN chown -R www-data:www-data /var/www/html
